### ISSUE TITLE
Frostbite-Scripts [frostbite3]

### ISSUE THREAD

**Issue by Morpheus100** [NicknineTheEagle/Frostbite-Scripts#1]
Hello
I have a problem with unpacking files in NFS Rivals
After changing the path in the [dumper] file and after running it throws me an error.
![1](https://user-images.githubusercontent.com/47033329/51752408-b5a36880-20b7-11e9-89cf-e449e5bd1813.PNG)

**Comment by NicknineTheEagle** [comment]
You've pointed the script at the wrong path, you need to set the var to the game root.

**Comment by Morpheus100** [comment]
how to do it ?

**Comment by NicknineTheEagle** [comment]
Just fix the the game path you're using in the script.

**Comment by Morpheus100** [comment]
I changed the path and there is also an error

gameDirectory   = r"D:\Electronic Arts\Need for Speed Rivals"
targetDirectory = r"D:\NFSR\dump"

![2](https://user-images.githubusercontent.com/47033329/51753015-18493400-20b9-11e9-9c63-0613d92f94fb.PNG)

**Comment by NicknineTheEagle** [comment]
Please, read README, it clearly states the scripts require Python 3.

**Comment by Morpheus100** [comment]
And the script is created for the version of Python 3.
Sorry, I did not notice xd

Thanks for your help (y)
