### ISSUE TITLE
Unable to dump Battlefront II

### ISSUE THREAD

**Issue by oogaoogabooga** [NicknineTheEagle/Frostbite-Scripts#10]
Hello, first time using github and stuff like this so please be patient.

So far I am unable to dump Battlefront 2 at all, I can dump Battlefront I, but for Battlefront 2 it detects all the cas and such but only dumps the guidtable. Is this perhaps caused by the change in file structure some of the updates have brought?

Is the Frostbite 3 dumper script able to dump Battlefront II? Or am I screwing something up? All my paths are correct.

**Comment by NicknineTheEagle** [comment]
The script does not support Battlefront II right now. It's planned but no estimates.
