### ISSUE TITLE
.res file conversion

### ISSUE THREAD

**Issue by cheif22** [NicknineTheEagle/Frostbite-Scripts#12]
Hi,

is there any way to convert .res texture files yet?

if there is, what method should i use?

Thanks in advance

**Comment by NicknineTheEagle** [comment]
Well, I know there are tools for converting Frostbite textures but I don't have a link, you'll have to Google it. Problem is, the old tools only work with old style chunk naming (which is incorrect), they won't work with my dumps. I'm planning to add support for TextureAsset conversion, just never got around to it.

**Comment by NicknineTheEagle** [comment]
Nope, sorry.
