### ISSUE TITLE
[Request] NFS: Heat

### ISSUE THREAD

**Issue by GHUser23** [NicknineTheEagle/Frostbite-Scripts#13]
Don't know if this is the proper way to suggest something on GitHub but I'd appreciate it if you could add support for NFS: Heat. I'd really like to extract the audio files for the police dialogue. It's almost as good as NFS: TR.

**Comment by NicknineTheEagle** [comment]
Eventually.

**Comment by GHUser23** [comment]
Sweet. Thanks.
