### ISSUE TITLE
I have a problem for extracting NFS rivals assets

### ISSUE THREAD

**Issue by mammadfh** [NicknineTheEagle/Frostbite-Scripts#17]
![MP1](https://user-images.githubusercontent.com/61066018/74565849-61e81380-4f87-11ea-9ee5-de65a96ea202.jpg)
All pathes are correct. Dumping was successful but I cannot use ebxtoasset. I Have installed all libs. plz help me developer.

**Comment by NicknineTheEagle** [comment]
Last time I checked NFS: Rivals, it was extracting fine. It's likely that a chunk was corrupted during the extraction, I saw that happen before. Try re-dumping the game.
