### ISSUE TITLE
It only creates guidtTable.bin when I run the script

### ISSUE THREAD

**Issue by sfb22ua** [NicknineTheEagle/Frostbite-Scripts#18]
Evidence: https://imgur.com/L3W8jJq

**Comment by NicknineTheEagle** [comment]
gameDirectory var should point at the root game directory (where exe is).

**Comment by sfb22ua** [comment]
Isn’t there a way to modify the script to dump certain folders? I used to use some old scripts that were made for BF3 and they let me do that. I want to dump some X360 DLC .sb files with these scripts cause the old ones didn’t dump them correctly into .ebx so I hope including xbdecompress.exe does the job.

**Comment by NicknineTheEagle** [comment]
There's no such functionality due to technical specifics of how the script works.
