### ISSUE TITLE
When I dump X360 files I get this error

### ISSUE THREAD

**Issue by sfb22ua** [NicknineTheEagle/Frostbite-Scripts#19]
I managed to make a workaround to dump certain files by removing everything of the Data folder in game’s directory and leaving only the ones that I want to be dumped. It works fine for the PC files but when I try with X360 ones I get this error either seconds after I run the script or after it dumped some files already: https://imgur.com/SVVgExq

**Comment by NicknineTheEagle** [comment]
NFS: The Run X360 extracts fine with the scripts I provided. I will not fix your custom code for you.
