### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Morpheus100** [NicknineTheEagle/Frostbite-Scripts#2]
Hey

I have a question, do you have any information about any scripts or tools to extract songs from the titles of Need For Speed (2015) , Need For Speed Payback ?

**Comment by NicknineTheEagle** [comment]
My FB3 scripts work with both games. After you dumped the games, use ebxtoasset script to extract audio files from chunks. All music is in audio/music. Sounds are stored in standard SPS format which can be decoded with appropriate EA audio tools.

**Comment by Morpheus100** [comment]
The [frostbite3] package will separate songs from Nfs (2015) and Nfa Payback?

**Comment by NicknineTheEagle** [comment]
Yes, read README, it clearly describes what each script is for.

**Comment by Morpheus100** [comment]
One more question, did you create such a script? do you cooperate with someone in creating a scripts?

**Comment by Morpheus100** [comment]
Thanks again for helping

**Comment by NicknineTheEagle** [comment]
All credits are in README.
