### ISSUE TITLE
Mass Effect Andromeda

### ISSUE THREAD

**Issue by kloruklass** [NicknineTheEagle/Frostbite-Scripts#22]
I successfully dumped Mass Effects Andromeda but the files won't be converted to wave format with fb3decoder and ealayer. Whenever I run the script it scans the files and then it gets stuck in some kind of error. I tried to remove the folders/files with the errors but this didn't fix the issue. Now I have 30gb+ of useless chunks.

**Comment by NicknineTheEagle** [comment]
I do not provide support for third party tools.
