### ISSUE TITLE
Error when trying to run dumper.py

### ISSUE THREAD

**Issue by 13Stewartc** [NicknineTheEagle/Frostbite-Scripts#25]
> Traceback (most recent call last):
>   File "d:\Stews-Stuff\13Stewartc\(A) Tools\Frostbite Scripts\frostbite3\dumper.py", line 7, in <module>
>     import payload
>   File "d:\Stews-Stuff\13Stewartc\(A) Tools\Frostbite Scripts\frostbite3\payload.py", line 8, in <module>
>     liblz4 = ctypes.cdll.LoadLibrary(r"..\thirdparty\liblz4")
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 452, in LoadLibrary
>     return self._dlltype(name)
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> FileNotFoundError: Could not find module 'C:\Users\thirdparty\liblz4' (or one of its dependencies). Try using the full path with constructor syntax.

Same error happens if the frostbite scripts folder is anywhere on my system. Adding thirdparty to C:\Users\ removes this error but generates a new one. (still fails). I have Python 3.9 Windows Store edition as well as the standard edition installed.

**Comment by NicknineTheEagle** [comment]
Your working directory is set to `C:\Users` while it should be the dir where dumper.py is.

**Comment by 13Stewartc** [comment]
Using Visual Studio Code to run the script. Appreciate your suggestion, set the workspace to the correct location, but it keeps throwing a different error now :/ Too many errors, not worth my time. Appreciate your help.
