### ISSUE TITLE
[Request] Please add support for localized voicelines

### ISSUE THREAD

**Issue by Simo311** [NicknineTheEagle/Frostbite-Scripts#27]
This script is unable to extract the localized voicelines for games like Battlefield 3/4, it does ONLY extract the English ones.
It's been years since i'm trying to get italian or other's languages voicelines from these two games, i would immensely apreciate if you could help me with that!

**Comment by NicknineTheEagle** [comment]
This is not a dumper issue. It extracts everything but to get localized voice lines you must have them installed to begin with. Origin only installs localization files for the selected language. Switch your game to Italian in game properties. If you there's no such option, you're out of luck.

**Comment by Simo311** [comment]
But my game has never been in English.
When i installed the game I choose Italian, and the game plays so.

**Comment by NicknineTheEagle** [comment]
It should extract all localized SPS with different numbers at the end, that's how it works in NFS: The Run.

**Comment by Simo311** [comment]
Yes, you're right! Bf4 extraction dumped the voicelines for every language!! 
But sadly not for bf3, all I got is English audio files, that's really strange... It's like it ignored every other languages beside English... Any suggestions?
Also does this script also works with newer Battlefield games? Like Battlefield 1 and V or 2042 open beta? it would be very unfortunate to perform the extraction and finding out that only English voicelines has been extracted.
Thanks a ton!

**Comment by NicknineTheEagle** [comment]
It should work with BF1 but not BFV or later. See README.
For BF3, when you run dumper script, do italian superbundles show up in the log (should be loc/it.toc).

**Comment by Simo311** [comment]
Not so sure about Italian superbundle in the log, but in the raw extraction bundles\ebx\localization i have 12 files belonging to different localization, inlcunding it_loc.ebx
They are small though...

**Comment by NicknineTheEagle** [comment]
What do you get after parsing voice lines with ebxtotext? Just one SPS per EBX?

**Comment by Simo311** [comment]
Nothing because ebxtoasset operates only within the bundles\ebx\localization\sound folder and it's subfolders, and the localization folder that I pointed at you it's just outside of it, should i include everything in the ebxtoasset convert process?

**Comment by NicknineTheEagle** [comment]
What? I said voice lines, not localization folder you mentioned. If all the voice lines aren't in localization\sound, then they're clearly elsewhere.

> ebxtoasset should extract all localized SPS with different numbers at the end when parsing SoundWaveAsset with localized sounds, that's how it works in NFS: The Run.

**Comment by Simo311** [comment]
The English voicelines i have are all coming from bundles\ebx\sound\vo and there o have 2 folders, one called EN (containing all the English localization voicelines) and another one named common (containing all the voicelines shared within all the differents version of the game) but no francais/spanish/italian voices has been found.
So clearly there something missing here.

**Comment by NicknineTheEagle** [comment]
What's inside sound\vo? Just one SPS per EBX with no numbers? Also, can you run ebxtotext on sound/vo folder and post the result?

**Comment by NicknineTheEagle** [comment]
https://github.com/EmulatorNexus/Venice-EBX/blob/master/Sound/VO/EN/MP/Gamemode/Radio/vo_us_mp_gm_gen_inform_losing_big_r.txt
This lists multiple languages with 8 variations per each. Each language is in its own chunk. This is same setup as NFS: The Run so you should get different languages upon parsing with ebxtoasset, English would be something like vo_us_mp_gm_gen_inform_losing_big_r 7 0 0.sps, Frech would be vo_us_mp_gm_gen_inform_losing_big_r 0 0 0.sps, etc.

**Comment by Simo311** [comment]
> https://github.com/EmulatorNexus/Venice-EBX/blob/master/Sound/VO/EN/MP/Gamemode/Radio/vo_us_mp_gm_gen_inform_losing_big_r.txt This lists multiple languages with 8 variations per each. Each language is in its own chunk. This is the same setup as NFS: The Run so you should get different languages upon parsing with ebxtoasset, English would be something like vo_us_mp_gm_gen_inform_losing_big_r 7 0 0.sps, French - vo_us_mp_gm_gen_inform_losing_big_r 0 0 0.sps, Italian - vo_us_mp_gm_gen_inform_losing_big_r 1 0 0.sps, etc.

Thanks a lot! 
Sorry for the late responses but I'm being very busy with my job. 
Anyway I'm going to test it by myself as soon as I can, I'll let you know. 
thanks a lot!!!

**Comment by NicknineTheEagle** [comment]
Is this still relevant?

**Comment by Simo311** [comment]
> Is this still relevant?

Yeah sorry, I did not have time since then to try it out :(
