### ISSUE TITLE
It does not extract all Nfs 2016 songs

### ISSUE THREAD

**Issue by Morpheus100** [NicknineTheEagle/Frostbite-Scripts#3]
Hi, I wanted to inform you that the [dumper] script from the [frostbite3] folder does not extract all the songs from Need For Speed 2016. I miss four songs are:

Aero Chord - Break Them (feat. Anna Yvette)
Clement Marfo & The Frontline - Get Rowdy
CP feat. Danny Cainco - Do not Stop
Dirty South - The Unknown (feat. FMLYBND)

Is it possible to solve this problem?

The words you are reading are explained by Google -> Translator

**Comment by NicknineTheEagle** [comment]
Perhaps you are not looking in the right place then, Frostbite games have a lot of sounds scattered around different folders. Assuming these songs actually play in-game and aren't a port of a video.

**Comment by Morpheus100** [comment]
I searched and found nothing
I even typed the words individual to ( Search ) in Windows and found nothing
unless the scribe does not unpack the various files and bypasses.
Do you do something about it?

The words you are reading are explained by Google -> Translator

**Comment by NicknineTheEagle** [comment]
SoundWaveAsset is the only sound asset type used by this game. Either this track has a non-indicative name or you're not looking in the right place.

**Comment by NicknineTheEagle** [comment]
CP feat. Danny Cainco - Do not Stop is named Party_Camelphat_Stop. Like I said, they appear to have confusing names.

**Comment by Morpheus100** [comment]
Ok this song is skipping his mistake
CP feat. Danny Cainco - Do not Stop

**Comment by NicknineTheEagle** [comment]
The rest of these aren't even listed in GenenisMusicAsset.ebx. Where are those songs used? In cutscenes?

**Comment by NicknineTheEagle** [comment]
https://nfssoundtrack.com/nfs2015/

This page confirms these songs are only used in cutscenes. Which means they're a part of movie audio tracks and you're out of luck. Do your research next time.

**Comment by Morpheus100** [comment]
I did not mean to offend you only to say that something is wrong with the script.

**Comment by Morpheus100** [comment]
does that mean that songs 3 are in movies in the game anyway?

**Comment by NicknineTheEagle** [comment]
Like I said, they're probably in movie audio tracks mixed in with the rest of cutscene audio. You can check ui/movies directory, MovieTextureAsset assets will you get VP6 files that you can convert and listen to.

**Comment by Morpheus100** [comment]
ok, I'll check it right now.

**Comment by Morpheus100** [comment]
MovieTextureAsset is a program?

**Comment by NicknineTheEagle** [comment]
No, it's one of Frostbite asset types handled by ebxtoasset scripts.

**Comment by Morpheus100** [comment]
ok

**Comment by Morpheus100** [comment]
How should I change in the script to extract movies?

**Comment by NicknineTheEagle** [comment]
Please, learn how to read instructions already. All scripts are explained in README and comments in the script itself.

**Comment by Morpheus100** [comment]
ok przepraszam

**Comment by Morpheus100** [comment]
ok thanks for help
you can already close the topic.
