### ISSUE TITLE
Add the `partitionGUID` aka `fileGUID`

### ISSUE THREAD

**Issue by FlashHit** [NicknineTheEagle/Frostbite-Scripts#31]
Add this `f2.write("Partition "+self.fileGUID.format()+"\n")` here:
https://github.com/NicknineTheEagle/Frostbite-Scripts/blob/master/frostbite3/ebx.py#L464
and here:
https://github.com/NicknineTheEagle/Frostbite-Scripts/blob/master/frostbite2/ebx.py#L409

When I mod I usually do sth like `ResourceManager:FindInstanceByGuid(partitionGuid, instanceGuid)`. If I just have the instanceGuid then it would take longer to find that instance. That's why it makes sense to add this.

**Comment by NicknineTheEagle** [comment]
Done here: https://github.com/NicknineTheEagle/Frostbite-Scripts/commits/master.
