### ISSUE TITLE
Errno 13: Permission denied

### ISSUE THREAD

**Issue by AFK-Jose** [NicknineTheEagle/Frostbite-Scripts#35]
Dear Nicknine,
If you wish to, can you make a step-by-step instruction guide in running the scripts you've made? It will be of great help so that I won't get so many errors in executing the scripts

**Comment by NicknineTheEagle** [comment]
Firstly, information on using the scripts is provided in README document. If you don't understand it, I can't help you.
Secondly, what errors are you getting?

**Comment by AFK-Jose** [comment]
Errno 13: Permission denied when I tried accessing a file from the dumped assets

**Comment by NicknineTheEagle** [comment]
That sounds pretty odd. This after running the dumper script, right? What exactly are you trying to do?

**Comment by AFK-Jose** [comment]
Yes, and I'm trying to access the mesh assets to convert them into FBX or any other 3D formats

**Comment by NicknineTheEagle** [comment]
This script set to does not support mesh assets, I thought we've established already. I do not provide support for third-party tools.

**Comment by AFK-Jose** [comment]
Ok, apologies
