### ISSUE TITLE
What needs to be done to make this work with 2018+ games?

### ISSUE THREAD

**Issue by loganfuller** [NicknineTheEagle/Frostbite-Scripts#4]
I'm trying to extract assets from Anthem and this seems to be the closest repo from what I've seen so far. Do you know what areas need to be updated to get this to work with modern games? I'd be happy to help out if you could point me in the right direction.

Also - do you have any idea how to pull the directory structure / file names from .sb files? I'm hoping to map out the directory structure of Anthem first and then to work on extracting the actual assets.

**Comment by NicknineTheEagle** [comment]
Anthem uses new format not seen before, it completely changed TOC and SB format and is seemingly missing cas.cat files there are just cas_xx.cas. Nobody has figured this layout out yet. FIFA 19 is a weird and confusing mess that I don't understand. BF5 and SWBF2 have a dumper script for them that I'm planning integrate later.
