### ISSUE TITLE
Need For Speed: Rivals doesn't seem to extract all chunks properly

### ISSUE THREAD

**Issue by ProjectHSI** [NicknineTheEagle/Frostbite-Scripts#41]
Launcher:
EA Desktop

Using Frostbite 3 scripts.
"ebxtoasset.py" fails on most assets with "Chunk not found {chunk here}"

**Comment by NicknineTheEagle** [comment]
Unable to reproduce, tested with `audio\music` directory, all assets extract fine. What ebx are you getting missing chunks on?

**Comment by ProjectHSI** [comment]
Currently extracting from a clean repo. (Cleared all modifications)
Paths are set correctly.
I'll get back to you as soon as I can.

**Comment by ProjectHSI** [comment]
Here's the configuration for the python scripts:
dumper.py:
gameDirectory   = r"D:\Origin\Origin Games\Need for Speed(TM) Rivals"
targetDirectory = r"D:\VGDumps\Need For Speed Rivals\Dump"

ebxtoasset.py:
targetDirectory = r"D:\VGDumps\Need For Speed Rivals\Dump"
targetDirectory = r"D:\VGDumps\Need For Speed Rivals\Assets"
inputFolder     = r"" #relative to ebxFolder, am i supposed to be doing this?

ebxtotext.py:
targetDirectory = r"D:\VGDumps\Need For Speed Rivals\Dump"
targetDirectory = r"D:\VGDumps\Need For Speed Rivals\Scripts"
inputFolder     = r"" #relative to ebxFolder

i'm using ebxtoasset.py and ebxtotext.py to extract all assets.
also frosty editor seems to work fine for this game.
Once again, once the dumping process is done. I'll back to you.

**Comment by ProjectHSI** [comment]
I'm also performing this test dump on a brand new dump. There shouldn't any problems related to files already existing.

**Comment by ProjectHSI** [comment]
In addition, here's the DLC I have for this game. Prices are probably in AUD.
<img width="1250" alt="NFSR DLC 1" src="https://user-images.githubusercontent.com/57279339/235380613-18c9c74d-e687-4b3d-a155-62f88dddd3e9.png">
<img width="1239" alt="NFSR DLC 2" src="https://user-images.githubusercontent.com/57279339/235380605-29a72ff6-9a2c-4e5c-93ca-eb30e63472ac.png">
<img width="1234" alt="NFSR DLC 3" src="https://user-images.githubusercontent.com/57279339/235380610-d1417d0e-64ae-4bb9-9dce-b7652b6ec64e.png">

**Comment by ProjectHSI** [comment]
^ errors with the dump directory have been fixed, i was copy and pasting all around and in my haste i just did that mistake
it didn't produce an error, i just missed it so i just modified it

**Comment by ProjectHSI** [comment]
Dumper.py reports no errors or weird behavior.

**Comment by ProjectHSI** [comment]
Ebxtotext.py works fine.

**Comment by ProjectHSI** [comment]
Ebxtoasset.py, after condensing it's output down to just the chunk guids at fault. Returns at 226kb file which only contains the guids with no repeats.
(Done with notepad++)
[assetGenerationOutput.txt](https://github.com/NicknineTheEagle/Frostbite-Scripts/files/11362741/assetGenerationOutput.txt)

**Comment by NicknineTheEagle** [comment]
Please, provide ebx names, chunk ids don't tell me anything.

**Comment by NicknineTheEagle** [comment]
Will close this if ebx names are not provided soon.

**Comment by ProjectHSI** [comment]
i don't have enough motivation to write a regex that checks for faulty ebx names at this time
closing
