### ISSUE TITLE
[BF1] I dumped the game, but can't ebxtoX ?

### ISSUE THREAD

**Issue by vrpixel** [NicknineTheEagle/Frostbite-Scripts#46]
Hi, I edited the .py files with my paths, I dumped the game successfully, it took quite a while, but now I'm trying to use the ebxtotext/ebxtoasset I just get this:

Loading GUID table...
Loading RES table...

And nothing else. I'm trying to extract all the audio. Any ideas what's wrong?

Thanks!

**Comment by NicknineTheEagle** [comment]
Did you fill out all the parameters? Make sure inputFolder points to the desired subdirectory in ebx path. In case of ebxtoasset, the directory must also actually contain EBX assets of a supported type.

**Comment by vrpixel** [comment]
OK, I changed the inputFolder, I thought by default it will process everything.
However, it seems like I'm getting .SPS files out of it, rather than .WAV. Do I need some sort of converter?

Apparently I need vgmstream, but it's a command line tool. Can you guide me how to batch convert the entire dump?

**Comment by NicknineTheEagle** [comment]
vgmstream comes in several forms besides CLI tool, there are also plugins for foobar2000, WinAmp and other players. They let you play the game audio files directly.
If you still want to mass convert everything, you can make a bat script with CLI tool. Like this:
```bat
@echo off

for /F %%A in ('dir *.sps /b /s') do (
	test.exe -o %%~pA%%~nA.wav -i %%A
)

pause
```

**Comment by NicknineTheEagle** [comment]
Assuming the issue is resolved.
