### ISSUE TITLE
Battlefield Hardline 

### ISSUE THREAD

**Issue by kosolapi** [NicknineTheEagle/Frostbite-Scripts#47]
When i try to run ebxtoasset.py or ebxtotext.py they only show `Loading GUID table...
Loading RES table...` even after hours of running no new messages. 
dumper.py worked with no issues

https://imgur.com/a/6AcW4yJ

**Comment by NicknineTheEagle** [comment]
It didn't ran for hours, it finished running instantly cause you didn't specify a valid subfolder to scan - you can see the three arrows at the bottom. Edit inputFolder variable and specify which folder to scan for assets to extract.
