### ISSUE TITLE
ebxtoasset.py doesn't work on BF4 dump files

### ISSUE THREAD

**Issue by karpuzikov** [NicknineTheEagle/Frostbite-Scripts#49]
I've made dump with dumper.py of bf4 steam release, but ebxtoasset.py does nothing
it shows 
`Loading GUID table...

Loading RES table...

PS C:\extract\Frostbite-Scripts-master\frostbite3>`
and that's it

**Comment by NicknineTheEagle** [comment]
Did you update inputFolder parameter to point to the subfolder you want to the parse?

**Comment by karpuzikov** [comment]
yes ofc

**Comment by NicknineTheEagle** [comment]
Show me the parameters you have set.

**Comment by karpuzikov** [comment]
import os
from struct import unpack,pack
import ebx
import res

#Choose where you dumped the files and where to put the extracted assets.
dumpDirectory   = r"C:\DUMP\Battlefield 4 DUMP"
targetDirectory = r"C:\DUMP\Battlefield 4 DUMP assets"
inputFolder     = r"audio" #relative to ebxFolder

#These paths are relative to the dumpDirectory. They don't need to be changed.
ebxFolder    = r"bundles\ebx"
resFolder    = r"bundles\res"
chunkFolder  = r"chunks"
chunkFolder2 = r"bundles\chunks" #if the chunk is not found in the first folder, use this one

#Run through the sound ebx files, find fields with chunk Guids and fieldName = ChunkId.
#The script will overwrite existing files.

#The filename of the ebx file importing an audio chunk becomes the name of the wav file.
#There are three indices used in the following order.
#1: Variation.ChunkIndex: Some ebx files import several completely independent audio chunk files. This index differentiates between them.
#2: Variation.Index: An ebx may use the same audio chunk for several sound variations, this index keeps them apart.
#3: Segment.Index: A variation may contain several segments, so there is another index.

##############################################################
##############################################################

ebxFolder,chunkFolder,chunkFolder2,resFolder = [os.path.join(dumpDirectory, path) for path in (ebxFolder, chunkFolder, chunkFolder2, resFolder)]
inputFolder=os.path.join(ebxFolder,inputFolder)

print("Loading GUID table...")
ebx.loadGuidTable(dumpDirectory)
print ("Loading RES table...")
res.loadResTable(dumpDirectory)

for dir0, dirs, ff in os.walk(inputFolder):
    for fname in ff:
        dbx=ebx.Dbx(os.path.join(dir0,fname),ebxFolder)
        dbx.extractAssets(chunkFolder,chunkFolder2,resFolder,targetDirectory)

**Comment by karpuzikov** [comment]
![{5AA1FB10-E12E-4988-B912-5535140F7D15}](https://github.com/user-attachments/assets/ddd5ef61-cce0-4733-bcaf-14111a9ccdf8)

**Comment by karpuzikov** [comment]
i've done already extraction of nfs run, nfs rivals, bf3. and this problem only with bf4

**Comment by NicknineTheEagle** [comment]
Is there actually a folder called "audio" inside bundles/ebx?

**Comment by karpuzikov** [comment]
no, there is not 
![{0868ACB0-0496-4007-9725-655858458907}](https://github.com/user-attachments/assets/f01b21b5-f643-438b-8ec4-d074e8a9cac2)

**Comment by NicknineTheEagle** [comment]
I've asked you whether you updated inputFolder and you said yes. Yet it's set to a path that doesn't exist.

**Comment by karpuzikov** [comment]
oh man... my bad, didn't save changes in text editor. thank you
