### ISSUE TITLE
how the hell do you use this thing?

### ISSUE THREAD

**Issue by BootlegTheMagician** [NicknineTheEagle/Frostbite-Scripts#50]
i'm new to python and have no idea how to use this

**Comment by NicknineTheEagle** [comment]
Maybe try reading the included instructions instead of angrily demanding other people to chew your food for you.

**Comment by BootlegTheMagician** [comment]
the included instructions are very vague.

**Comment by BootlegTheMagician** [comment]
and a question isnt a demand, nor am i mad, im really confused

**Comment by BootlegTheMagician** [comment]
im literally trying everything i can and nothing is working.

**Comment by mistyrosetta** [comment]
Maybe try to actually use your brain to read and understand the actual thing, it was hard for me but I managed to did it, so it's doable.
