### ISSUE TITLE
How can I extract Need for Speed Unbound files correctly?

### ISSUE THREAD

**Issue by Pixela8** [NicknineTheEagle/Frostbite-Scripts#51]
Hi!

Since I found your Python scripts about extracting files (I'm very interested to get the meshes/collisions) inside the game root, I'm getting errors. I tried to fixing the paths, even created a folder named Dump inside my hard drive directory and not in Users folder. Well I still not suceed to do it.

I also installed the latest Python version today like marked in the README.md file.

I did almost all things for running scripts correctly without errors.

Do you know if there is any solutions?

Thanks for readed my request.

Pixela8.

😄

**Comment by NicknineTheEagle** [comment]
Unfortunately, NFS: Unbound is not supported. See README for more details.

**Comment by Pixela8** [comment]
Okay, no problems.
