### ISSUE TITLE
Ao2 the devils cartel.

### ISSUE THREAD

**Issue by OrangeC88** [NicknineTheEagle/Frostbite-Scripts#6]
Hello im getting this error. its the PS3 version of the game. have all the DLL's in the same dir as the script.
![image](https://user-images.githubusercontent.com/51392143/58927300-0ee16f80-871c-11e9-85e2-ada9a3153498.png)

**Comment by NicknineTheEagle** [comment]
You're using the wrong script, Army of Two runs on Frostbite 2.
