### ISSUE TITLE
Need For Speed the Run Will Not Extract.

### ISSUE THREAD

**Issue by GHUser23** [NicknineTheEagle/Frostbite-Scripts#7]
When I run **dumper.py** on Need For Speed the Run, it gives me this error.

![Capture_1](https://user-images.githubusercontent.com/52847988/61167537-95088700-a50e-11e9-9255-ad08f70bac2a.PNG)

**Comment by NicknineTheEagle** [comment]
Huh, how did that slip through? Fixed in https://github.com/NicknineTheEagle/Frostbite-Scripts/commit/23d9b6ceb44adcf6ad8309b444839f0481e6d0b7.
