### ISSUE TITLE
NFS 2015 Access Violation Error

### ISSUE THREAD

**Issue by GHUser23** [NicknineTheEagle/Frostbite-Scripts#8]
After running **dumper.py** on NFS: 2015, I am met with this access violation error:

![Capture1](https://user-images.githubusercontent.com/52847988/61196506-1e4dc400-a69d-11e9-8787-39e9e6d6e79d.PNG)

**Comment by NicknineTheEagle** [comment]
That... wasn't happening before. I didn't change anything related to zstd lib ever since updating all libs to 64-bit. Maybe Windows 10 broke the library somehow? 🤷‍♂

**Comment by NicknineTheEagle** [comment]
Fixed in https://github.com/NicknineTheEagle/Frostbite-Scripts/commit/efecb9e86963040c5fcd4eb75bbd97dbc0fdf045. I swear it used to work before.
