### ISSUE TITLE
Can't use ebxtoasset

### ISSUE THREAD

**Issue by bobbin4dicks** [NicknineTheEagle/Frostbite-Scripts#9]
I'm trying to convert ebx files to sound files for my dumps of DA:I, Battlefront and Battlefront II, but it just stalls.

Am I doing something wrong? I have all the paths correctly setup. Am I using the wrong version of Python?
![Python_3 7 4_Shell_2019-07-15_19-58-03](https://user-images.githubusercontent.com/52940246/61256563-383de400-a73b-11e9-8d50-192aa6e6e0f8.png)

**Comment by GHUser23** [comment]
The last time I saw this happen, I had the file paths incorrectly spelled. Make sure that your file paths for TARGET and GAME/DUMP directory are EXACTLY spelled correctly and correct.

It could also just take a while. These games are quite complex nowadays.

**Comment by bobbin4dicks** [comment]
Thanks for the quick response.

Paths are all correct(after all I'm just copying the address as text and pasting it in).

Been running it for a few hours now, still no results.

**Comment by NicknineTheEagle** [comment]
Three arrows appear (command line) appear when the script is finished so it didn't find anything at all. Post your config from the top of the script here.

**Comment by bobbin4dicks** [comment]
Ah I see, I was just an idiot, I didn't set the inputFolder to the appropriate sound folders.

Now though I am getting the sound extracted as sps files rather than wavs.

**Comment by NicknineTheEagle** [comment]
That's how it's supposed to work. It does not convert assets, it just extracts from chunks. SPS is standard EA audio format, google it.

**Comment by bobbin4dicks** [comment]
I see how it is, I'm justvery used to just running a script that makes the wavs too when taking the ebx assets through ealayer, thanks though.
